### ISSUE TITLE
Exemplo de uso do GIT

### ISSUE THREAD

**Issue by viniconceicao** [skkysz/ExemploGit#1]
O professor passou as seguintes tarefas para realizar:

- Crie um repositório local e integre ele ao remoto criado anteriormente, ExemploGit. • Ajuste, especificamente para esse repositório, user.name e user.email, respectivamente para Abc Bolinhas e abc@bolinhas.com
- Crie uma nova branch chamada NovoProjeto
- Dentro do diretório do repositório local, Crie um novo projeto Kotlin e nele realize somente a escrita do seu nome completo no console.
- Os diretórios out, .idea não devem ser versionados.
- Suba as alterações realizadas na branch NovoProjeto para o remoto, realizando a
- anotação na issue criada, e também já realizando seu fechamento.
- Realize o MERGE no remoto, branchs envolvidas:
    - NovoProjeto e Main
- Após realizar o merge, remova a branch NovoProjeto
- No local, retorne e atualize o conteúdo da branch main
- Remova a branch NovoProjeto

**Comment by viniconceicao** [comment]
Foi realizado as alterações, agora será realizado o MERGE e o fechamento da Issue

**Comment by skkysz** [comment]
Foi realizado as alterações, agora será realizado o MERGE e o fechamento da Issue
